/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchListenRouteImport } from './routes/watch-listen'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as LearnAiRouteImport } from './routes/learn-ai'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CivicGuideRouteImport } from './routes/civic-guide'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanguageNumbersRouteImport } from './routes/language.numbers'

const WatchListenRoute = WatchListenRouteImport.update({
  id: '/watch-listen',
  path: '/watch-listen',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAiRoute = LearnAiRouteImport.update({
  id: '/learn-ai',
  path: '/learn-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CivicGuideRoute = CivicGuideRouteImport.update({
  id: '/civic-guide',
  path: '/civic-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageNumbersRoute = LanguageNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => LanguageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/civic-guide': typeof CivicGuideRoute
  '/history': typeof HistoryRoute
  '/language': typeof LanguageRouteWithChildren
  '/learn-ai': typeof LearnAiRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watch-listen': typeof WatchListenRoute
  '/language/numbers': typeof LanguageNumbersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/civic-guide': typeof CivicGuideRoute
  '/history': typeof HistoryRoute
  '/language': typeof LanguageRouteWithChildren
  '/learn-ai': typeof LearnAiRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watch-listen': typeof WatchListenRoute
  '/language/numbers': typeof LanguageNumbersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/civic-guide': typeof CivicGuideRoute
  '/history': typeof HistoryRoute
  '/language': typeof LanguageRouteWithChildren
  '/learn-ai': typeof LearnAiRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watch-listen': typeof WatchListenRoute
  '/language/numbers': typeof LanguageNumbersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/civic-guide'
    | '/history'
    | '/language'
    | '/learn-ai'
    | '/people'
    | '/sitemap.xml'
    | '/watch-listen'
    | '/language/numbers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/civic-guide'
    | '/history'
    | '/language'
    | '/learn-ai'
    | '/people'
    | '/sitemap.xml'
    | '/watch-listen'
    | '/language/numbers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/civic-guide'
    | '/history'
    | '/language'
    | '/learn-ai'
    | '/people'
    | '/sitemap.xml'
    | '/watch-listen'
    | '/language/numbers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CivicGuideRoute: typeof CivicGuideRoute
  HistoryRoute: typeof HistoryRoute
  LanguageRoute: typeof LanguageRouteWithChildren
  LearnAiRoute: typeof LearnAiRoute
  PeopleRoute: typeof PeopleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchListenRoute: typeof WatchListenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch-listen': {
      id: '/watch-listen'
      path: '/watch-listen'
      fullPath: '/watch-listen'
      preLoaderRoute: typeof WatchListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-ai': {
      id: '/learn-ai'
      path: '/learn-ai'
      fullPath: '/learn-ai'
      preLoaderRoute: typeof LearnAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civic-guide': {
      id: '/civic-guide'
      path: '/civic-guide'
      fullPath: '/civic-guide'
      preLoaderRoute: typeof CivicGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language/numbers': {
      id: '/language/numbers'
      path: '/numbers'
      fullPath: '/language/numbers'
      preLoaderRoute: typeof LanguageNumbersRouteImport
      parentRoute: typeof LanguageRoute
    }
  }
}

interface LanguageRouteChildren {
  LanguageNumbersRoute: typeof LanguageNumbersRoute
}

const LanguageRouteChildren: LanguageRouteChildren = {
  LanguageNumbersRoute: LanguageNumbersRoute,
}

const LanguageRouteWithChildren = LanguageRoute._addFileChildren(
  LanguageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CivicGuideRoute: CivicGuideRoute,
  HistoryRoute: HistoryRoute,
  LanguageRoute: LanguageRouteWithChildren,
  LearnAiRoute: LearnAiRoute,
  PeopleRoute: PeopleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchListenRoute: WatchListenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
